version: "2.1"
services:
  micros.go.mod:
    image: micros.go.mod
    build:
      context: ./
      dockerfile: ./Dockerfile.mod
  github.handler:
    labels:
      svc: "github-handler"
    restart: always
    build:
      context: ./ # esta variable se sobreescribe Ejm. docker-compose.prod.yaml
      dockerfile: ./Dockerfile
      args:
        - app=github-handler
    ports:
      - 5555:5555
    env_file:
      - ./.env
